### ISSUE TITLE
ACME? [Feature Request]

### ISSUE THREAD

**Issue by Identitry** [theelims/ESP32-sveltekit#42]
Such a cool project, I must come up with a something where I can use this!

...Now that it has stable HTTPS support it would be cool if you also include an ACME-client for pulling certs also!?

There's a library already available that I think might fit:
https://sourceforge.net/projects/esp32-acme-client/

**Comment by theelims** [comment]
Well, there is currently no support for TLS/SSL for the web-server. Although the underlying PsychicHttp does support it, it is not yet implemented. Mainly because of the enormous heap resources and the limitation to 2 sockets. It is on the long-term roadmap though. 

One of the requirements is, that this projects must not relay on internet access to work properly. Which makes SSL certificate validation quite tricky. I'll keep your link in mind once the project has evolved into that state. 

You're welcome to provide a pull request to add that SSL functionality and the certificate download. However, from my side I'll close this issue, as it is on the long-term roadmap already.
